### PR TITLE
Use the common language

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by kyrias** [comment]
Comments are fine, but I will not add the `--lang` option like that. I'd be fine with some command option I guess, but currently phrik's `g` alias adds `--lang en`.

**Comment by polyzen** [comment]
> currently phrik's g alias adds --lang en.

This doesn't appear to do the trick.

`--exact` might also be nice to have available:
` -x, --exact           disable automatic spelling correction`

**Comment by kyrias** [comment]
Example of what doesn't work? Works quite well overall for me.On Jun 20, 2017 11:03, "Daniel M. Capella" <notifications@github.com> wrote:
currently phrik's g alias adds --lang en.

This doesn't appear to do the trick.
--exact might also be nice to have available:
-x, --exact disable automatic spelling correction

**Comment by polyzen** [comment]
Seems this was applied after the bot was restarted.

Before:
> !g pineapple mitm
> polyzen: Studenten wollten ihre Freunde mit einer Ananas veräppeln, wurden ... <http://www.galileo.tv/life/studenten-wollten-ihre-freunde-mit-einer-ananas-veraeppeln-wurden-deshalb-zu-kuenstlern-erklaert/>

After:
> !g pineapple mitm
> polyzen: The WiFi Pineapple - Using Karma and SSLstrip to MiTM secure ... <https://scotthelme.co.uk/wifi-pineapple-karma-sslstrip/>

**Comment by kyrias** [comment]
Phrik hasn't changed for weeks or months by now. The only restarts are restarts of the server he's on, so if it the result has changed in the last few weeks it's just Google's nondeterminism.On Jun 20, 2017 11:30, "Daniel M. Capella" <notifications@github.com> wrote:Seems this was applied after the bot was restarted.
Before:

!g pineapple mitm
polyzen: Studenten wollten ihre Freunde mit einer Ananas veräppeln, wurden ... http://www.galileo.tv/life/studenten-wollten-ihre-freunde-mit-einer-ananas-veraeppeln-wurden-deshalb-zu-kuenstlern-erklaert/

After:

!g pineapple mitm
polyzen: The WiFi Pineapple - Using Karma and SSLstrip to MiTM secure ... https://scotthelme.co.uk/wifi-pineapple-karma-sslstrip/

**Pull request closed without merging**
